### ISSUE TITLE
sproto的sublime的高亮问题请教 

### ISSUE THREAD

**Issue by yksalun** [lvzixun/sublime-sproto-syntax#1]
你好，我在sublime上安装了您的sproto插件，之后打开sproto文件的格式是这样的：
![image](https://cloud.githubusercontent.com/assets/7500277/9782540/79c53716-57d0-11e5-9b39-8a2cc5a7ca1e.png)
而我在您的github主页上的readme中看到您贴的高亮的格式是这样的：
![image](https://cloud.githubusercontent.com/assets/7500277/9782549/9757f890-57d0-11e5-984f-b0f1135b83a4.png)
sublime2和sublime3都试过了，都是一样的。
以上两图对照下来看，应该是消息类型名没有高亮，是要做什么设置么还是我下的插件有问题呢？
ps:本来想发gmail的，但是foxmail发送不了，所以到这里来提issues了：(

**Comment by lvzixun** [comment]
`sproto_type`的类别为`entity.name.type`。每个类别显示的style是根据你应用的sublime的theme来设定的。我自己的sublime应用的theme为: [monokai extended](https://github.com/jonschlinkert/sublime-monokai-extended)。 你可以换下试试 ;)

**Comment by yksalun** [comment]
It is work! thx! :)
